"""
Django settings for RRHHPromaco project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9=147@sp4k#o)6t7yp#^dh^#*m-8pjne6l(ixzz_v9t*u0n=m0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['settled-lamprey-sincerely.ngrok-free.app', '*']
CSRF_TRUSTED_ORIGINS = ['https://settled-lamprey-sincerely.ngrok-free.app']
CSRF_COOKIE_SECURE = False
# Application definition

# RRHHPromaco/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reclutamiento',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/Dashboard/'  # Cambia '/dashboard/' a la URL que corresponda
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Almacena las sesiones en la base de datos
AUTH_USER_MODEL = 'reclutamiento.Users'  # Reemplaza 'tu_app' con el nombre real de tu aplicación
AUTHENTICATION_BACKENDS = [
    'reclutamiento.backends.DNIAuthBackend', 
    'django.contrib.auth.backends.ModelBackend'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reclutamiento.middlewares.LoginRequiredMiddleware',
    'reclutamiento.middlewares.PermissionRequiredMiddleware',
]

ROOT_URLCONF = 'RRHHPromaco.urls'

# RRHHPromaco/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'RRHHPromaco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'RRHH_Promaco',
        'USER': 'mmelgar',
        'PASSWORD': 'KensPlay_7212',
        'HOST': '127.0.0.1',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;',  # Opcional para evitar problemas SSL
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Tegucigalpa'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# RRHHPromaco/settings.py

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'reclutamiento/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directorio donde se recopilan todos los archivos estáticos




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
